version: 0.2
phases:
  build:
    commands:
      - which python
      - whereis python
      - python --version
  install:
    commands:
      - aws cloudformation package --template-file sam_template.yaml --s3-bucket awsconfig-20190214010335263400000004 --output-template-file output_sam_template.yaml
artifacts:
  type: zip
  files:
    - input_sam_template.yaml
    - output_sam_template.yaml
