version: 0.2
phases:
  build:
    commands:
      - which python
      - whereis python
      - python --version
      - python test.py
  install:
    commands:
      - aws cloudformation package --template-file inputSAMTemplate.yaml --s3-bucket asjdlksajdkjsal --output-template-file outputSAMTemplate.yaml
artifacts:
  type: zip
  files:
    - inputSAMTemplate.yaml
    - outputSAMTemplate.yaml
