
version: 0.2
phases:
  install:
    commands:
      - pip install unittest --user || exit 0
      - pip install unittest || exit 0
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket asjdlksajdkjsal --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
