
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Prints Hello World
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: my_handler
      Runtime: python3.7    
      CodeUri: ./
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /HelloWorld
            Method: GET
